#Torch Burn Duration
[torch_duration]
#Age required before torch degrades. A value of 5 lasts approximately 17 minutes on average.
#Flimsy Torch Age (Default: 5)
#Range: 0 ~ 15
flimsyTorchAge = 15
#Used Torch Age (Default: 5)
#Range: 0 ~ 15
usedTorchAge = 15
#Smoldering Torch Age (Default: 5)
#Range: 0 ~ 15
smolderingTorchAge = 15

#Other Torches
[other_torches]
#List of torches from other mods to be replaced by flimsy torches if generated.
#Ground torches to be replaced
otherGroundTorches = ["othermod:other_torch", "anothermod:another_torch"]
#Wall torches to be replaced
otherWallTorches = ["othermod:other_wall_torch", "anothermod:another_wall_torch"]

#General Settings
[general]
#Chance of a generated torch to remain a regular, non-flimsy torch (Default: 0.01 - 1%)
#Range: 0.0 ~ 1.0
chanceLuckyTorch = 0.0

#Villager Torch Behavior
[villager_torch_behavior]
#Interval between each attempt to replace a torch. A value of 20 equals 1 second.
#Torch Replace Interval. (Default: 100)
#Range: > 1
torchReplaceInterval = 6000
#Defines which torch types villagers are allowed to replace. Lower condition torches are prioritized first.
#Allow villagers to replace Burnt Out torches
allowBurntOutReplacement = true
#Allow villagers to replace Smoldering Torches
allowSmolderingReplacement = true
#Allow villagers to replace Used Torches
allowUsedReplacement = false